title: Scott Membry
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2712137
  brandStrength: 0.375
  lightness: 0.5350568
  brandColors:
    - '#012D88'
    - '#01BBB0'
    - '#AC003A'
    - '#FFE958'
    - '#FF868D'
  rhythmicContrast: 0.11495
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Scott Membry
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.49849
layout_spectrum: 0.24791
