title: Scott Membry
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2712137
  brandStrength: 0.4763695
  lightness: 0.5350568
  brandColors:
    - '#0212DB'
    - '#DE5E91'
    - '#4291EE'
    - '#8CD25E'
    - '#BE10B0'
  rhythmicContrast: 0.11495
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Scott Membry
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.49849
layout_spectrum: 0.24791
