name: scottmembry
favicon: null
layout_spectrum: 0.7632626686245203
typography_spectrum: 0.2569579058326781
title: ScottMembry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3276676337700337
  lightness: 0.5350568045396358
  saturation: 0.049751512706279755
  rhythmicContrast: 0.11494997655972838
purpose: []
