name: Scott Membry
favicon: null
layout_spectrum: 0.24791
typography_spectrum: 0.49849
title: Scott Membry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#092049'
    - '#7990a3'
    - '#ecf2ee'
    - '#c6ced8'
    - '#2d384f'
  brandStrength: 0.375
  lightness: 0.5350568045396358
  saturation: 0.049751512706279755
  rhythmicContrast: 0.11494997655972838
purpose: []
